//{{NO_DEPENDENCIES}}
// Microsoft Visual C++ generated include file.
// Used by NoteBuilderFrame.rc
//
#define IDC_BUTTON_APP_THRESHOLD        2
#define IDC_BUTTON_APP_PIXELS           3
#define IDC_BTN_BROWSE                  3
#define IDOK4                           4
#define IDC_BUTTON_APP_WINDOW           4
#define IDC_BTN_READ_SIZE               4
#define IDC_BUTTON_BROWSE               5
#define IDC_BUTTON_APP_PIXELS2          5
#define IDC_BUTTON_DEBUG                6
#define IDC_BUTTON_TEST                 7
#define IDC_BUTTON_COPY_DATA            7
#define IDC_BUTTON_APP_PERCENT          8
#define IDC_APPLY_UNDISTORT             9
#define IDC_BUTTON_APP_PERCENT2         9
#define IDC_TEST_TREE                   9
#define IDC_RESET                       10
#define IDC_TEST_SELECTION              11
#define IDC_TEST_EDGES                  12
#define IDD_ABOUTBOX                    100
#define IDP_OLE_INIT_FAILED             100
#define IDP_SOCKETS_INIT_FAILED         104
#define IDR_POPUP_EDIT                  119
#define ID_STATUSBAR_PANE1              120
#define ID_STATUSBAR_PANE2              121
#define IDS_STATUS_PANE1                122
#define IDS_STATUS_PANE2                123
#define IDS_TOOLBAR_STANDARD            124
#define IDS_TOOLBAR_CUSTOMIZE           125
#define ID_VIEW_CUSTOMIZE               126
#define IDR_MAINFRAME                   128
#define IDR_MAINFRAME_256               129
#define IDR_STCurrencyStudiTYPE         130
#define ID_WINDOW_MANAGER               131
#define IDS_WINDOWS_MANAGER             132
#define ID_VIEW_FILEVIEW                133
#define ID_VIEW_CLASSVIEW               134
#define ID_PROPERTIES                   135
#define ID_OPEN                         136
#define ID_OPEN_WITH                    137
#define ID_DUMMY_COMPILE                138
#define ID_CLASS_ADD_MEMBER_FUNCTION    139
#define ID_CLASS_ADD_MEMBER_VARIABLE    140
#define ID_CLASS_DEFINITION             141
#define ID_CLASS_PROPERTIES             142
#define ID_NEW_FOLDER                   143
#define ID_SORT_MENU                    144
#define ID_SORTING_GROUPBYTYPE          145
#define ID_SORTING_SORTALPHABETIC       146
#define ID_SORTING_SORTBYTYPE           147
#define ID_SORTING_SORTBYACCESS         148
#define ID_VIEW_OUTPUTWND               149
#define ID_VIEW_PROPERTIESWND           150
#define ID_SORTPROPERTIES               151
#define ID_PROPERTIES1                  152
#define ID_PROPERTIES2                  153
#define ID_EXPAND_ALL                   154
#define IDS_FILE_VIEW                   155
#define IDS_CLASS_VIEW                  156
#define IDS_OUTPUT_WND                  157
#define IDS_PROPERTIES_WND              158
#define IDI_FILE_VIEW                   161
#define IDI_FILE_VIEW_HC                162
#define IDI_CLASS_VIEW                  163
#define IDI_CLASS_VIEW_HC               164
#define IDI_OUTPUT_WND                  165
#define IDI_OUTPUT_WND_HC               166
#define IDI_PROPERTIES_WND              167
#define IDI_PROPERTIES_WND_HC           168
#define IDR_EXPLORER                    169
#define IDB_EXPLORER_24                 170
#define IDR_SORT                        171
#define IDB_SORT_24                     172
#define IDR_POPUP_SORT                  173
#define IDR_POPUP_EXPLORER              174
#define IDB_FILE_VIEW                   175
#define IDB_FILE_VIEW_24                176
#define IDB_CLASS_VIEW                  177
#define IDB_CLASS_VIEW_24               178
#define IDR_MENU_IMAGES                 179
#define IDB_MENU_IMAGES_24              180
#define ID_TOOLS_MACRO                  181
#define IDR_OUTPUT_POPUP                182
#define IDR_PROPERTIES                  183
#define IDB_PROPERTIES_HC               184
#define IDS_CLOSE                       195
#define IDR_THEME_MENU                  200
#define ID_SET_STYLE                    201
#define ID_VIEW_APPLOOK_WIN_2000        210
#define ID_VIEW_APPLOOK_OFF_XP          211
#define ID_VIEW_APPLOOK_WIN_XP          212
#define ID_VIEW_APPLOOK_OFF_2003        213
#define ID_VIEW_APPLOOK_VS_2005         214
#define ID_VIEW_APPLOOK_OFF_2007_BLUE   215
#define ID_VIEW_APPLOOK_OFF_2007_BLACK  216
#define ID_VIEW_APPLOOK_OFF_2007_SILVER 217
#define ID_VIEW_APPLOOK_OFF_2007_AQUA   218
#define IDS_BUILD_TAB                   300
#define IDS_DEBUG_TAB                   301
#define IDS_FIND_TAB                    302
#define IDS_EXPLORER                    305
#define IDS_EDIT_MENU                   306
#define IDD_CURRENCY_INFO               310
#define IDD_REGION_TEST                 311
#define IDR_HTML_REGIONTESTDLG          312
#define IDD_SELECT_REGION               312
#define IDD_SERIAL_TEST                 313
#define IDD_OCR                         314
#define IDD_OCR_SAVE                    315
#define IDD_IMAGE_TEST_DLG              316
#define IDD_BUILDLOG                    317
#define IDD_EXTRACT_IMAGE               318
#define IDD_WINDEBUG                    320
#define IDR_MENU1                       321
#define IDR_MENU_DUMMY                  321
#define IDD_CALIBRATION                 322
#define IDD_SETTING                     322
#define IDD_DIALOG1                     323
#define IDD_COPY_MSG                    324
#define IDD_DEBUG_MSG                   324
#define IDC_EDIT_CURNAME                1000
#define IDC_EDIT_CURCODE                1000
#define IDC_EDIT_CURNUMBER              1001
#define IDC_EDIT_CURDENOMVALUES         1002
#define IDC_EDIT_RECT_REG1              1003
#define IDC_EDIT_RECT_REG2              1004
#define IDC_EDIT_RECT_REG_NNR           1004
#define IDC_COMBO_IMAGE_REG1            1005
#define IDC_EDIT_IMG_IMG                1005
#define IDC_EDIT_IMG_NUM                1005
#define IDC_EDIT_EXTENSION              1005
#define IDC_COMBO_IMAGE_REG2            1006
#define IDC_BUTTON_GENKEYS              1007
#define IDC_BUTTON_GENKEYS_1            1007
#define IDC_BUTTON_MAKEREF              1008
#define IDC_EDIT_SX                     1008
#define IDC_BUTTON_MAKEREF_1            1008
#define IDC_BUTTON_TESTREF              1009
#define IDC_EDIT_EX                     1009
#define IDC_COMBO_METHOD_REG1           1010
#define IDC_EDIT_SY                     1010
#define IDC_BUTTON_GENKEYS_2            1010
#define IDC_COMBO_METHOD_REG2           1011
#define IDC_EDIT_EY                     1011
#define IDC_BUTTON_MAKEREF_2            1011
#define IDC_BUTTON_EXTRACT_DATA         1011
#define IDC_COMBO_CURRENCY_LIST         1012
#define IDC_EDIT_THREAD_WIDTH           1012
#define IDC_COMBO_CURRENCY_LIST2        1013
#define IDC_COMBO_REGIONS               1013
#define IDC_EDIT_DECX                   1013
#define IDC_EDIT_DECI_REG1              1014
#define IDC_EDIT_DECY                   1014
#define IDC_EDIT_SUM_REG1               1015
#define IDC_EDIT_SUMX                   1015
#define IDC_EDIT_DECI_REG2              1016
#define IDC_EDIT_SUMY                   1016
#define IDC_BUTTON_GATHER_DATA          1016
#define IDC_EDIT_SUM_REG2               1017
#define IDC_BUTTON_EXTRACT              1017
#define IDC_BUTTON_EXECUTE_NNR          1017
#define IDC_EDIT_THRES_REG1             1018
#define IDC_EDIT_DEGREE                 1018
#define IDC_EDIT_THRES_REG2             1019
#define IDC_EDIT_W_AVG                  1019
#define IDC_BUTTON_DEF_REG1             1020
#define IDC_EDIT_IR_AVG                 1020
#define IDC_BUTTON_DEF_REG2             1021
#define IDC_EDIT_CURVERSIONS            1022
#define IDC_BUTTON_FIND_THREAD          1022
#define IDC_EDIT_CURVERSIONS2           1023
#define IDC_EDIT_W_MIN                  1023
#define IDC_BUTTON_TESTREF2             1024
#define IDC_BUTTON_LOADREF              1024
#define IDC_COMBO_REGION_TYPE           1024
#define IDC_EDIT_THREAD_AVG             1025
#define IDC_BUTTON_SEL1                 1025
#define IDC_EDIT_THREAD_POS             1026
#define IDC_BUTTON_SEL2                 1026
#define IDC_BUTTON_SAVE_RECOG_METHOD    1026
#define IDC_COMBO_IMAGE_SOURCE          1027
#define IDC_COMBO_IMAGE_SOURCE_1        1027
#define IDC_BUTTON_ANALYZE_THREAD       1028
#define IDC_COMBO_REINFORCEMENT         1028
#define IDC_EDIT_IR_AVG2                1029
#define IDC_EDIT_KEY_FOLDER_1           1029
#define IDC_CLOSE                       1030
#define IDC_COMBO_IMAGE_SOURCE_2        1030
#define IDC_COMBO_RECOG_METHOD          1030
#define IDC_COMBO_DIRECTION             1031
#define IDC_EDIT_KEY_FOLDER_2           1031
#define IDC_EDIT_THREAD_SIZE            1032
#define IDC_BUTTON_KEY_FOLDER_2         1032
#define IDC_BUTTON_GENERATE             1033
#define IDC_BUTTON_KEY_FOLDER_1         1033
#define IDC_EDIT_THREAD_SIDE            1034
#define IDC_EDIT_DSP_FOLDER             1034
#define IDC_EDIT_DLL_NAME               1034
#define IDC_BUTTON_DELETE               1035
#define IDC_BUTTON_DSP_FOLDER           1035
#define IDC_BUTTON_SAVE                 1036
#define IDC_EDIT_KEY_FOLDER             1036
#define IDC_EDIT_EXT_FOLDER             1036
#define IDC_BUTTON_DELETE2              1036
#define IDC_COMBO_VALUE                 1037
#define IDC_BUTTON_KEY_FOLDER           1037
#define IDC_BUTTON_EXT_FOLDER           1037
#define IDC_COMBO_DIRECTION3            1038
#define IDC_EDIT_REF_FOLDER             1038
#define IDC_EDIT_DST_FOLDER             1038
#define IDC_COMBO_R00                   1039
#define IDC_EDIT_RESULT                 1039
#define IDC_BUTTON_REF_FOLDER           1039
#define IDC_BUTTON_DST_FOLDER           1039
#define IDC_CHECK_SHOW                  1040
#define IDC_BUTTON_SAVE2                1040
#define IDC_BUTTON_NO_DRAW              1040
#define IDC_EDIT_PREFIX                 1040
#define IDC_COMBO_R01                   1041
#define IDC_BUTTON_TEST_NNR             1041
#define IDC_COMBO_R10                   1042
#define IDC_COMBO_R11                   1043
#define IDC_COMBO_R20                   1044
#define IDC_EDIT_XSIZE                  1044
#define IDC_COMBO_R21                   1045
#define IDC_EDIT_YSIZE                  1045
#define IDC_COMBO_R30                   1046
#define IDC_EDIT_MAX_REF                1046
#define IDC_COMBO_R31                   1047
#define IDC_EDIT_CUR_CODE               1047
#define IDC_COMBO_R40                   1048
#define IDC_EDIT_CUR_NBR                1048
#define IDC_COMBO_R41                   1049
#define IDC_COMBO_R50                   1050
#define IDC_COMBO_R51                   1051
#define IDC_COMBO_R60                   1052
#define IDC_COMBO_R61                   1053
#define IDC_EDIT_IR_MIN                 1054
#define IDC_COMBO_R70                   1055
#define IDC_EDIT_W_MAX                  1056
#define IDC_EDIT_IR_AVG4                1057
#define IDC_EDIT_IR_MAX                 1057
#define IDC_BUTTON_RELOAD               1058
#define IDC_COMBO_CIS_ENC               1058
#define IDC_EDIT_W_VAR                  1059
#define IDC_EDIT_IR_VAR                 1060
#define IDC_BUTTON_SEPARATE             1061
#define IDC_BUTTON_SAVE_SER_IMG         1063
#define IDC_COMBO_R71                   1075
#define IDC_EDIT_REG_IDX                1076
#define IDC_EDIT_REG_NAME               1077
#define IDC_LABEL_RESULT0               1102
#define IDC_LABEL_RESULT1               1103
#define IDC_LABEL_RESULT2               1104
#define IDC_LABEL_RESULT3               1105
#define IDC_LABEL_RESULT4               1106
#define IDC_LABEL_RESULT5               1107
#define IDC_LABEL_RESULT6               1108
#define IDC_LABEL_RESULT7               1109
#define IDC_LIST_REGION                 1110
#define IDC_BUTTON_SELECT               1112
#define IDC_BUTTON_IR_AND_W             1117
#define IDC_LIST2                       1118
#define IDC_BUTTON_OCR                  1118
#define IDC_LIST_IMAGE                  1119
#define IDC_EDIT_W_THRESHOLD            1120
#define IDC_EDIT_IR_THRESHOLD           1121
#define IDC_EDIT_W_PIXELS               1122
#define IDC_EDIT_IR_PIXELS              1123
#define IDC_EDIT_C0                     1123
#define IDC_EDIT_H_WINDOW               1124
#define IDC_EDIT_C1                     1124
#define IDC_EDIT_READ                   1124
#define IDC_EDIT_V_WINDOW               1125
#define IDC_EDIT_C2                     1125
#define IDC_EDIT_TOT_PIXELS             1126
#define IDC_EDIT_C3                     1126
#define IDC_EDIT_HALF_PIXELS            1127
#define IDC_EDIT_NOF_CHARS              1127
#define IDC_EDIT_C4                     1127
#define IDC_EDIT_C5                     1128
#define IDC_EDIT_H_WINDOW2              1128
#define IDC_EDIT_NNR_FOLDER             1129
#define IDC_EDIT_C6                     1129
#define IDC_EDIT_W_PERCENT              1129
#define IDC_EDIT_C7                     1130
#define IDC_EDIT_V_WINDOW2              1130
#define IDC_EDIT_C8                     1131
#define IDC_EDIT_NNR_HEIGHT             1131
#define IDC_EDIT_V_WIN2                 1131
#define IDC_EDIT_C9                     1132
#define IDC_EDIT_IR_PERCENT             1132
#define IDC_EDIT_W_PCENT                1132
#define IDC_EDIT_C10                    1133
#define IDC_EDIT_IR_PIXELS2             1133
#define IDC_EDIT_IR_PCENT               1133
#define IDC_EDIT_C11                    1134
#define IDC_EDIT_W_THRESHOLD2           1134
#define IDC_EDIT_LEAST_PIXEL            1134
#define IDC_EDIT_C12                    1135
#define IDC_EDIT_NNR_LOADMARK           1135
#define IDC_EDIT_C13                    1136
#define IDC_EDIT_W_PIXELS_R             1136
#define IDC_EDIT_C14                    1137
#define IDC_EDIT_IR_PIXELS_R            1137
#define IDC_EDIT_C15                    1138
#define IDC_EDIT_SAVE_FOLDER            1139
#define IDC_BUTTON_LOAD_NNR             1140
#define IDC_EDIT_SAVE_HEIGHT            1140
#define IDC_LIST_OCR                    1141
#define IDC_CHECK_AUTO_NNR              1142
#define IDC_CHECK_AUTO_EXTRACT          1142
#define IDC_COMBO_SOURCE                1143
#define IDC_CHECK_SERIAL_IMAGE          1143
#define IDC_EDIT1                       1144
#define IDC_EDIT_MSG                    1144
#define IDC_CFLEVEL0                    1144
#define IDC_EDIT_COPY                   1144
#define IDC_CHECK_AUTO_NNR2             1144
#define IDC_CHECK_V_RESIZE              1144
#define IDC_COMBO_NNRNO                 1144
#define IDC_EDIT_NNR_LOADED             1144
#define IDC_TH_MIN                      1144
#define IDC_COMBO_HMETHOD               1145
#define IDC_EDIT_K1                     1145
#define IDC_COMBO_THR_TYPE              1146
#define IDC_CFLEVEL1                    1146
#define IDC_CHECK_AUTO_EXTRACT2         1146
#define IDC_CHECK_BY_DENOM              1146
#define IDC_EDIT_K2                     1146
#define IDC_TAPE_LEVEL                  1147
#define IDC_COMBO_SOURCE2               1147
#define IDC_COMBO_SCALE                 1147
#define IDC_COMBO_SCALEX                1147
#define IDC_EDIT_K3                     1147
#define IDC_HOLE_LEVEL                  1148
#define IDC_COMBO_SCALEY                1148
#define IDC_EDIT_FOCUS                  1148
#define IDC_THETA                       1148
#define IDC_DEINKKED_LEVEL              1149
#define IDC_EDIT_LEFT                   1149
#define IDC_MAX_LINE_GAP                1149
#define IDC_SOILE_LEVEL0                1150
#define IDC_EDIT_TOP                    1150
#define IDC_EDGE_LINE_MIN_X             1150
#define IDC_STAIN_LEVEL                 1151
#define IDC_EDIT_WIDTH                  1151
#define IDC_THRESHOLD                   1151
#define IDC_WASHED_LEVEL                1152
#define IDC_EDIT_HEIGHT                 1152
#define IDC_MIN_LINE_LENGTH             1152
#define IDC_SOILE_LEVEL1                1153
#define IDC_EDIT_RECT0                  1153
#define IDC_EDGE_LINE_MAX_Y             1153
#define IDC_SOILE_LEVEL2                1154
#define IDC_EDIT_RECT1                  1154
#define IDC_EDGE_LINE_MAX_X             1154
#define IDC_SOILE_LEVEL3                1155
#define IDC_EDIT_RECT2                  1155
#define IDC_EDGE_LINE_MIN_Y             1155
#define IDC_SOILE_LEVEL4                1156
#define IDC_SCALE_WIDTH                 1156
#define IDC_EDGE_SLOPE_MAX_X            1156
#define IDC_SOILE_LEVEL5                1157
#define IDC_EDIT_HEIGHT2                1157
#define IDC_SCALE_HEIGHT                1157
#define IDC_EDGE_SLOPE_MAX_Y            1157
#define IDC_SOILE_LEVEL6                1158
#define IDC_EDIT_C16                    1158
#define IDC_EDGE_VAR_X                  1158
#define IDC_EDIT_K4                     1158
#define IDC_MAX_CHAR_HEIGHT             1158
#define IDC_EDIT_C17                    1159
#define IDC_EDGE_SLOPE_MIN_Y            1159
#define IDC_MIN_CHAR_HEIGHT             1159
#define IDC_EDIT_C18                    1160
#define IDC_THRESHOLD4                  1160
#define IDC_EDGE_VAR_Y                  1160
#define IDC_HORILINE_MIN_PIXELS         1160
#define IDC_EDIT_C19                    1161
#define IDC_HORILINE_VAR_ALLOW          1161
#define IDC_BUTTON_COPY_REGION          1162
#define IDC_EDIT_C20                    1162
#define IDC_VERTLINE_MIN_PIXELS         1162
#define IDC_LIST_DELETED                1163
#define IDC_EDIT_C21                    1163
#define IDC_HORILINE_VAR_ALLOW2         1163
#define IDC_VERTLINE_VAR_ALLOW          1163
#define IDC_EDIT_C22                    1164
#define IDC_EDGE_TO_MARK                1164
#define IDC_CHECK_COPY_KEY              1165
#define IDC_COMBO1                      1165
#define IDC_COMBO_FUNCTION              1165
#define IDC_EDIT_C23                    1165
#define IDC_PLATE_TYPE                  1165
#define IDC_CHECK_VIA_DLL               1166
#define IDC_EDIT_C24                    1166
#define IDC_BLUR_TYPE                   1166
#define IDC_CHECK2                      1167
#define IDC_CHECK_REGION_SET            1167
#define IDC_EDIT_C25                    1167
#define IDC_FITNESS_CHECK               1167
#define IDC_ENABLE_CROP                 1167
#define IDC_EDIT_C26                    1168
#define IDC_CHECK1                      1168
#define IDC_CHECK_REGION_SET2           1168
#define IDC_CHECK_TEST_THRU_TESTDLL     1168
#define IDC_CHECK_UNDISTORT             1168
#define IDC_EDIT_C27                    1169
#define IDC_EDIT_F_HEIGHT               1169
#define IDC_ENABLE_SCALE                1169
#define IDC_EDIT_C28                    1170
#define IDC_BUTTON1                     1170
#define IDC_EQUIDIST_METHOD             1170
#define IDC_EDIT_C29                    1171
#define IDC_SLIDER1                     1171
#define IDC_VAR_LIMIT                   1171
#define IDC_EDIT_C30                    1172
#define IDC_EDIT_E0                     1172
#define IDC_EDIT_C31                    1173
#define IDC_EDIT_E1                     1173
#define IDC_EDIT_C32                    1174
#define IDC_EDIT_E2                     1174
#define IDC_EDIT_C33                    1175
#define IDC_CANNY_RATIO                 1175
#define IDC_TH_MAX                      1175
#define IDC_EDIT_C34                    1176
#define IDC_CANNY_RATIO2                1176
#define IDC_KERNEL_SIZE                 1176
#define IDC_EDIT_C35                    1177
#define IDC_IMG_SELECT                  1177
#define IDC_EDIT_C36                    1178
#define IDC_NNR_FOLDER                  1178
#define IDC_GRID_W                      1178
#define IDC_EDIT_C37                    1179
#define IDC_IMG_TEXT                    1179
#define IDC_EDIT_C38                    1180
#define IDC_IMG_SAVE                    1180
#define IDC_VAR_LIMIT3                  1180
#define IDC_GRID_H                      1180
#define IDC_EDIT_C39                    1181
#define IDC_EDIT_C40                    1182
#define IDC_BROWSE_NNR_FOLDER           1182
#define IDC_EDIT_C41                    1183
#define IDC_EDIT2                       1183
#define IDC_SELECTED_RECT               1183
#define IDC_EDIT_C42                    1184
#define IDC_EDGES                       1184
#define IDC_EDIT_C43                    1185
#define IDC_ROH                         1185
#define IDC_EDIT_C44                    1186
#define IDC_EDGE_POINTS                 1186
#define IDC_CHECK3                      1186
#define IDC_TEST_HOUGH_LINE             1186
#define IDC_EDIT_C45                    1187
#define IDC_EDGE_SLOPE_MIN_X            1187
#define IDC_CHECK4                      1187
#define IDC_EDIT_C46                    1188
#define IDC_EDIT3                       1188
#define IDC_TESTED_EDGES                1188
#define IDC_EDIT_C47                    1189
#define IDC_MARK_THE_EDGE               1189
#define IDC_EDIT4                       1191
#define IDC_CHECK5                      1192
#define IDC_APPLY_FFT                   1192
#define IDC_APPLY_FFT2                  1193
#define IDC_NEW_CANNY                   1193
#define ID_EDIT_CURRENCY                32771
#define ID_EDIT_REMOVE                  32772
#define ID_VIEW_REGIONTESTER            32773
#define ID_CURRENCY_GENERATEREGIONRAW   32774
#define ID_GENERATE_REGION_RAW          32775
#define ID_VIEW_DEBUGIMAGE              32776
#define ID_FILE_RELOAD                  32777
#define ID_OCR                          32778
#define ID_VIEW_IMAGETESTER             32779
#define ID_VIEW_IMAGE_TESTER            32780
#define ID_CURRENCY_IMAGEFOLDER         32781
#define ID_CURRENCY_IMAGE_FOLDER        32782
#define ID_FILE_SOURCE                  32783
#define ID_VIEW_EXTRACT                 32784
#define ID_VIEW_FIXDLEDISTORTION        32785
#define ID_FIX_DISTORTION               32786
#define ID_VIEW_FIXDLEDISTORTION32789   32789
#define ID_VIEW_REINFORCEIMAGE          32790
#define ID_VIEW_REINFORCE_IMAGE         32791
#define ID_DEBUG_IPC                    32792
#define ID_CURRENCY_DATAMAKER           32793
#define ID_CURRENCY_CALIBRATION         32794
#define ID_CURRENCY_CALIBRATIION        32795
#define ID_DEBUG_SHOWDEBUG              32796
#define ID_VIEW_MG                      32797
#define ID_VIEW_UV                      32798
#define ID_VIEW_MG_UV_CIS               32799

// Next default values for new objects
// 
#ifdef APSTUDIO_INVOKED
#ifndef APSTUDIO_READONLY_SYMBOLS
#define _APS_NEXT_RESOURCE_VALUE        326
#define _APS_NEXT_COMMAND_VALUE         32800
#define _APS_NEXT_CONTROL_VALUE         1193
#define _APS_NEXT_SYMED_VALUE           313
#endif
#endif
